name: elct
description: "Electronic - Luxury E-Commerce App"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: ^8.1.0
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  geolocator: ^14.0.3

  # Firebase
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.3
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.6.0
  firebase_messaging: ^16.4.1
  flutter_local_notifications: ^22.0.1
  firebase_crashlytics: ^5.2.4
  firebase_analytics: ^12.4.3

  # State Management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^17.3.0

  # Utilities
  intl: ^0.20.2

  # Connectivity
  connectivity_plus: ^7.2.0

  # UI Components
  cached_network_image: ^3.3.1
  # Utils
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.5
  flutter_animate: ^4.5.0
  package_info_plus: ^10.2.0
  font_awesome_flutter: ^11.0.0
  flutter_native_splash: ^2.4.7
  firebase_app_check: ^0.4.5
  sign_in_with_apple: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.4
  build_runner: ^2.15.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
