import 'package:flutter/material.dart';

class IconMapper {
  static const Map<String, IconData> _iconMap = {
    'devices': Icons.devices,
    'checkroom': Icons.checkroom,
    'home_outlined': Icons.home_outlined,
    'spa_outlined': Icons.spa_outlined,
    'watch': Icons.watch,
    'sports_soccer': Icons.sports_soccer,
    'chair': Icons.chair,
    'toys': Icons.toys,
    'headphones': Icons.headphones,
    'local_cafe': Icons.local_cafe,
    'menu_book': Icons.menu_book,
    'fastfood': Icons.fastfood,
    'pets': Icons.pets,
    'directions_car': Icons.directions_car,
    'local_florist': Icons.local_florist,
    'diamond': Icons.diamond,
    'brush': Icons.brush,
    'laptop_mac': Icons.laptop_mac,
    'phone_iphone': Icons.phone_iphone,
    'stroller': Icons.stroller,
    'fitness_center': Icons.fitness_center,
    'shopping_bag': Icons.shopping_bag,
    'shopping_cart': Icons.shopping_cart,
    'storefront': Icons.storefront,
    'inventory_2': Icons.inventory_2,
    'category': Icons.category,
    'kitchen': Icons.kitchen,
    'blender': Icons.blender,
    'microwave': Icons.microwave,
    'tv': Icons.tv,
    'camera_alt': Icons.camera_alt,
    'videogame_asset': Icons.videogame_asset,
    'speaker': Icons.speaker,
    'earbuds': Icons.earbuds,
    'tablet_mac': Icons.tablet_mac,
    'desktop_windows': Icons.desktop_windows,
    'memory': Icons.memory,
    'print': Icons.print,
    'mouse': Icons.mouse,
    'keyboard': Icons.keyboard,
    'power': Icons.power,
    'lightbulb': Icons.lightbulb,
    'bed': Icons.bed,
    'weekend': Icons.weekend,
    'yard': Icons.yard,
    'restaurant': Icons.restaurant,
    'bakery_dining': Icons.bakery_dining,
    'icecream': Icons.icecream,
    'local_pizza': Icons.local_pizza,
    'egg': Icons.egg,
    'child_care': Icons.child_care,
    'crib': Icons.crib,
    'backpack': Icons.backpack,
    'school': Icons.school,
    'sports_esports': Icons.sports_esports,
    'sports_basketball': Icons.sports_basketball,
    'sports_tennis': Icons.sports_tennis,
    'pool': Icons.pool,
    'hiking': Icons.hiking,
    'two_wheeler': Icons.two_wheeler,
    'flight': Icons.flight,
    'beach_access': Icons.beach_access,
    'redeem': Icons.redeem,
    'card_giftcard': Icons.card_giftcard,
    'sell': Icons.sell,
    'local_offer': Icons.local_offer,
    'wallet': Icons.wallet,
    'payments': Icons.payments,
    'medication': Icons.medication,
    'health_and_safety': Icons.health_and_safety,
    'face': Icons.face,
    'content_cut': Icons.content_cut,
    'palette': Icons.palette,
    'construction': Icons.construction,
    'hardware': Icons.hardware,
    'cleaning_services': Icons.cleaning_services,
    'eco': Icons.eco,
    'agriculture': Icons.agriculture,
    'cruelty_free': Icons.cruelty_free,
    'store': Icons.store,
    'local_mall': Icons.local_mall,
    'point_of_sale': Icons.point_of_sale,
    'receipt_long': Icons.receipt_long,
    'receipt': Icons.receipt,
    'qr_code_scanner': Icons.qr_code_scanner,
    'barcode_reader': Icons.qr_code_scanner, // Mapped to qr_code_scanner as barcode_reader might not be in older flutter
    'loyalty': Icons.loyalty,
    'percent': Icons.percent,
    'discount': Icons.discount,
    'price_check': Icons.price_check,
    'price_change': Icons.price_change,
    'request_quote': Icons.request_quote,
    'currency_exchange': Icons.currency_exchange,
    'account_balance_wallet': Icons.account_balance_wallet,
    'credit_card': Icons.credit_card,
    'contactless': Icons.contactless,
    'local_shipping': Icons.local_shipping,
    'delivery_dining': Icons.delivery_dining,
    'inventory': Icons.inventory,
    'warehouse': Icons.warehouse,
    'assignment': Icons.assignment,
    'fact_check': Icons.fact_check,
    'production_quantity_limits': Icons.production_quantity_limits,
    'add_shopping_cart': Icons.add_shopping_cart,
    'remove_shopping_cart': Icons.remove_shopping_cart,
    'shopping_basket': Icons.shopping_basket,
    'shopping_cart_checkout': Icons.shopping_cart_checkout,
    'trolley': Icons.shopping_cart, // Mapped to shopping_cart as trolley might not exist
    'package_2': Icons.all_inbox, // Mapped to all_inbox as package_2 might not exist
    'support_agent': Icons.support_agent,
    'location_on': Icons.location_on,
    'map': Icons.map,
    'business_center': Icons.business_center,
    'apartment': Icons.apartment,
    'domain': Icons.domain,
    'groups': Icons.groups,
    'person': Icons.person,
    'badge': Icons.badge,
    'campaign': Icons.campaign,
    'new_releases': Icons.new_releases,
  };

  static IconData getIcon(String? iconName, {IconData fallback = Icons.category_outlined}) {
    if (iconName == null || iconName.isEmpty) return fallback;
    return _iconMap[iconName] ?? fallback;
  }
}
