// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBclpJtVGJOgEoKIgHH8FpqOZ61i-1I8D4',
    appId: '1:156963900259:web:609d3ddb1a1f80f1232156',
    messagingSenderId: '156963900259',
    projectId: 'electronics-3c376',
    authDomain: 'electronics-3c376.firebaseapp.com',
    storageBucket: 'electronics-3c376.firebasestorage.app',
    measurementId: 'G-GXY6LT53GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwsrrYIK67y9amE_YDluzthqg6-AToPik',
    appId: '1:156963900259:android:c61c12d220fd66e1232156',
    messagingSenderId: '156963900259',
    projectId: 'electronics-3c376',
    storageBucket: 'electronics-3c376.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM33XhzmDNgK7YBDJJd1Cl4iygmPZfT6s',
    appId: '1:156963900259:ios:a9f544306fd986f4232156',
    messagingSenderId: '156963900259',
    projectId: 'electronics-3c376',
    storageBucket: 'electronics-3c376.firebasestorage.app',
    iosBundleId: 'com.example.elct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM33XhzmDNgK7YBDJJd1Cl4iygmPZfT6s',
    appId: '1:156963900259:ios:a9f544306fd986f4232156',
    messagingSenderId: '156963900259',
    projectId: 'electronics-3c376',
    storageBucket: 'electronics-3c376.firebasestorage.app',
    iosBundleId: 'com.example.elct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBclpJtVGJOgEoKIgHH8FpqOZ61i-1I8D4',
    appId: '1:156963900259:web:1c2d09dc74537181232156',
    messagingSenderId: '156963900259',
    projectId: 'electronics-3c376',
    authDomain: 'electronics-3c376.firebaseapp.com',
    storageBucket: 'electronics-3c376.firebasestorage.app',
    measurementId: 'G-BX8Q6P0GPQ',
  );

}